//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public case_()
        {
            this.boardformfactorcase_ = new HashSet<boardformfactorcase_>();
        }
    
        public int id { get; set; }
        public int sizeid { get; set; }
        public int expansionslots { get; set; }
        public int fans { get; set; }
    
        public virtual basepart_ basepart_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boardformfactorcase_> boardformfactorcase_ { get; set; }
        public virtual casesize_ casesize_ { get; set; }
    }
}
