//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class gpu_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gpu_()
        {
            this.videoconnectorgpu_ = new HashSet<videoconnectorgpu_>();
        }
    
        public int id { get; set; }
        public int gpuinterfaceid { get; set; }
        public int chipfrequency { get; set; }
        public int videomemory { get; set; }
        public int memorybus { get; set; }
        public Nullable<int> recommendpower { get; set; }
    
        public virtual basepart_ basepart_ { get; set; }
        public virtual gpuinterface_ gpuinterface_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<videoconnectorgpu_> videoconnectorgpu_ { get; set; }
    }
}
