//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pr15Entities : DbContext
    {
        public pr15Entities()
            : base("name=pr15Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assembly_> assembly_ { get; set; }
        public virtual DbSet<basepart_> basepart_ { get; set; }
        public virtual DbSet<boardformfactorcase_> boardformfactorcase_ { get; set; }
        public virtual DbSet<case_> case_ { get; set; }
        public virtual DbSet<casesize_> casesize_ { get; set; }
        public virtual DbSet<certificate_> certificate_ { get; set; }
        public virtual DbSet<cpu_> cpu_ { get; set; }
        public virtual DbSet<fandimension_> fandimension_ { get; set; }
        public virtual DbSet<formfactor_> formfactor_ { get; set; }
        public virtual DbSet<gpu_> gpu_ { get; set; }
        public virtual DbSet<gpuinterface_> gpuinterface_ { get; set; }
        public virtual DbSet<hdd_> hdd_ { get; set; }
        public virtual DbSet<igpu_> igpu_ { get; set; }
        public virtual DbSet<manufacturer_> manufacturer_ { get; set; }
        public virtual DbSet<memorytype_> memorytype_ { get; set; }
        public virtual DbSet<motherboard_> motherboard_ { get; set; }
        public virtual DbSet<partassembly_> partassembly_ { get; set; }
        public virtual DbSet<parttype_> parttype_ { get; set; }
        public virtual DbSet<powersupply_> powersupply_ { get; set; }
        public virtual DbSet<processorcooler_> processorcooler_ { get; set; }
        public virtual DbSet<ram_> ram_ { get; set; }
        public virtual DbSet<socket_> socket_ { get; set; }
        public virtual DbSet<socketprocessorcooler_> socketprocessorcooler_ { get; set; }
        public virtual DbSet<ssd_> ssd_ { get; set; }
        public virtual DbSet<storagedevice_> storagedevice_ { get; set; }
        public virtual DbSet<storagedeviceinterface_> storagedeviceinterface_ { get; set; }
        public virtual DbSet<storagedevicetype_> storagedevicetype_ { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<videoconnector_> videoconnector_ { get; set; }
        public virtual DbSet<videoconnectorgpu_> videoconnectorgpu_ { get; set; }
    }
}
