//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class motherboard_
    {
        public int id { get; set; }
        public int socketid { get; set; }
        public int formfactorid { get; set; }
        public int memoryslots { get; set; }
        public int memorytypeid { get; set; }
        public int pcislots { get; set; }
        public int sataports { get; set; }
        public int usbports { get; set; }
    
        public virtual basepart_ basepart_ { get; set; }
        public virtual formfactor_ formfactor_ { get; set; }
        public virtual memorytype_ memorytype_ { get; set; }
        public virtual socket_ socket_ { get; set; }
    }
}
