//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ram_
    {
        public int id { get; set; }
        public int memorytypeid { get; set; }
        public int capacity { get; set; }
        public int count { get; set; }
        public int ghz { get; set; }
        public string timings { get; set; }
    
        public virtual basepart_ basepart_ { get; set; }
        public virtual memorytype_ memorytype_ { get; set; }
    }
}
