//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class socketprocessorcooler_
    {
        public int id { get; set; }
        public int socketid { get; set; }
        public int processorcoolerid { get; set; }
    
        public virtual processorcooler_ processorcooler_ { get; set; }
        public virtual socket_ socket_ { get; set; }
    }
}
