//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class storagedevice_
    {
        public int id { get; set; }
        public int capacity { get; set; }
        public int storagedeviceinterfaceid { get; set; }
        public int storagedevicetypeid { get; set; }
    
        public virtual basepart_ basepart_ { get; set; }
        public virtual hdd_ hdd_ { get; set; }
        public virtual ssd_ ssd_ { get; set; }
        public virtual storagedeviceinterface_ storagedeviceinterface_ { get; set; }
        public virtual storagedevicetype_ storagedevicetype_ { get; set; }
    }
}
