//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jocker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeals
    {
        public int AppeaLID { get; set; }
        public int UserID { get; set; }
        public int TargetID { get; set; }
        public string Text { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> ObjectID { get; set; }
    
        public virtual Statuses Statuses { get; set; }
        public virtual Targets Targets { get; set; }
        public virtual Users Users { get; set; }
    }
}
