//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jocker
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookLists
    {
        public int ListID { get; set; }
        public int UserID { get; set; }
        public int BookID { get; set; }
        public int ListTypeID { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Books Books1 { get; set; }
        public virtual ListTypes ListTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
