//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jocker
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookGenres
    {
        public int BookGenreID { get; set; }
        public int BookID { get; set; }
        public int GenreID { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
