//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jocker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UP01Entities : DbContext
    {
        public UP01Entities()
            : base("name=UP01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appeals> Appeals { get; set; }
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<BookGenres> BookGenres { get; set; }
        public virtual DbSet<BookLists> BookLists { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<ListTypes> ListTypes { get; set; }
        public virtual DbSet<Petitions> Petitions { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Targets> Targets { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
