//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class basepart_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public basepart_()
        {
            this.partassembly_ = new HashSet<partassembly_>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int manufacturerid { get; set; }
        public int parttypeid { get; set; }
        public string image { get; set; }
        public decimal price { get; set; }
    
        public virtual manufacturer_ manufacturer_ { get; set; }
        public virtual parttype_ parttype_ { get; set; }
        public virtual case_ case_ { get; set; }
        public virtual cpu_ cpu_ { get; set; }
        public virtual gpu_ gpu_ { get; set; }
        public virtual motherboard_ motherboard_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partassembly_> partassembly_ { get; set; }
        public virtual powersupply_ powersupply_ { get; set; }
        public virtual processorcooler_ processorcooler_ { get; set; }
        public virtual ram_ ram_ { get; set; }
        public virtual storagedevice_ storagedevice_ { get; set; }
    }
}
