//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class boardformfactorcase_
    {
        public int id { get; set; }
        public int caseid { get; set; }
        public int formfactorid { get; set; }
    
        public virtual case_ case_ { get; set; }
        public virtual formfactor_ formfactor_ { get; set; }
    }
}
