//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class powersupply_
    {
        public int id { get; set; }
        public int power { get; set; }
        public int fandimensionid { get; set; }
        public int certificationid { get; set; }
    
        public virtual basepart_ basepart_ { get; set; }
        public virtual certificate_ certificate_ { get; set; }
        public virtual fandimension_ fandimension_ { get; set; }
    }
}
