//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class processorcooler_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public processorcooler_()
        {
            this.socketprocessorcooler_ = new HashSet<socketprocessorcooler_>();
        }
    
        public int id { get; set; }
        public int fandimensionid { get; set; }
        public int heatpipes { get; set; }
        public int minspeed { get; set; }
        public int maxspeed { get; set; }
        public double noiselevel { get; set; }
    
        public virtual basepart_ basepart_ { get; set; }
        public virtual fandimension_ fandimension_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<socketprocessorcooler_> socketprocessorcooler_ { get; set; }
    }
}
