//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class videoconnectorgpu_
    {
        public int id { get; set; }
        public int gpuid { get; set; }
        public int videoconnectorid { get; set; }
    
        public virtual gpu_ gpu_ { get; set; }
        public virtual videoconnector_ videoconnector_ { get; set; }
    }
}
